require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.2.0
  SuggestExtensions: false

Metrics/ClassLength:
  Max: 180

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

